# permissions for end users to edit caserunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caserunner-editor-role
rules:
- apiGroups:
  - apps.linxs.com
  resources:
  - caserunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.linxs.com
  resources:
  - caserunners/status
  verbs:
  - get
