# permissions for end users to view caserunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caserunner-viewer-role
rules:
- apiGroups:
  - apps.linxs.com
  resources:
  - caserunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.linxs.com
  resources:
  - caserunners/status
  verbs:
  - get
