# permissions for end users to edit deployflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployflow-editor-role
rules:
- apiGroups:
  - apps.linxs.com
  resources:
  - deployflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.linxs.com
  resources:
  - deployflows/status
  verbs:
  - get
