# permissions for end users to edit nodescales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodescale-editor-role
rules:
- apiGroups:
  - apps.linxs.com
  resources:
  - nodescales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.linxs.com
  resources:
  - nodescales/status
  verbs:
  - get
