# permissions for end users to view nodescales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodescale-viewer-role
rules:
- apiGroups:
  - apps.linxs.com
  resources:
  - nodescales
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.linxs.com
  resources:
  - nodescales/status
  verbs:
  - get
